### PR TITLE
fix csrf-token missing

### PR DESCRIPTION
**Pull request by dev-hyperweb**
add csrf-token to http-header 

this fix for 
https://github.com/LiveHelperChat/livehelperchat/issues/1747

and fix for changeOnline status on /site_admin panel

### CODE REVIEW

**Comment by dev-hyperweb** [comment]
###NEVERMIND
php cron.php -s site_admin -c cron/util/generate_css -p 1 && gulp js-static

when upgrading, need to re-gerenerate Javascript static-file

**Comment by remdex** [comment]
Hi,
Sorry, but this fix is invalid.
1. Your pull request deletes new stuff from new LHC version.
2. csrf-token token is already passed in LHC. Version so it seems it's problem with your server. Please check demo if you reproduce on demo then create pull request with steps to reproduce.

**Comment by dev-hyperweb** [comment]
right, Next time I will check on demo first.
my production site upgrade since  2.8 ,,3.x 3.5 3.6 .. until now


I use this link when upgrade https://doc.livehelperchat.com/docs/upgrading/  

but in somecase need re-generate js/css file .
maybe need add it into same page docs. For help upgradable.

**Comment by remdex** [comment]
For sure it's not needed to regenerate... It's enough just to clear cache in browser and click clear cache in lhc back office :) unless you have some overrides you did.

**Pull request closed without merging**
