### PR TITLE
Highlight empty fields on form submit

### PR DESCRIPTION
**Pull request by Joeboyc2**
These are the file i have amended as discussed here: https://github.com/LiveHelperChat/livehelperchat/issues/536

### CODE REVIEW

**Comment by remdex** [comment]
Sorry, but I cannot merge this pull request because of low quality of code (no quates in post variable which will produce notices instantly) and broken functionality of old code. Also unrelated files changes to implementing functionality.

But thanks for effort :)

**Comment by Joeboyc2** [comment]
Hi @remdex 

Im sorry but, as far as i can see, all of these files need changing in order to achieve what is needed.

I initially tried quotes on the $_POST variables but they were not working.... i can add these back in and re-submit.

can you elaborate on the code that i have broken, all seems to work fine on my side.

also as i mentioned before this is a very basic implementation and there possibly an better way to do it

**Comment by timetrex** [comment]
@remdex This would be a welcome improvement to user feedback and make the chat feature that much more useful. Its clear that @Joeboyc2 is willing to work with you to bring the code up to your standards, he just needs you to be more specific as to where the problems are so those improvements can be made.

Quickly dismissing push requests with generic unhelpful comments sure isn't a way to foster an open source community and start to build a larger developer base that can help you going forward. I know you are busy, but taking the time at least offer some direction to potential contributors can go a long way now and for future contributors.

**Comment by ipso** [comment]
@remdex This would be a welcome improvement to user feedback and make the chat feature that much more useful. Its clear that @Joeboyc2 is willing to work with you to bring the code up to your standards, he just needs you to be more specific as to where the problems are so those improvements can be made.

Quickly dismissing push requests with generic unhelpful comments sure isn't a way to foster an open source community and start to build a larger developer base that can help you going forward. I know you are busy, but taking the time at least offer some direction to potential contributors can go a long way now and for future contributors.

**Comment by PeopleInside** [comment]
Hi,
don't worry about: the topic is already opened, just closed the pull request for look into better code, i think, as soon @remdex can improve this :-)

**Pull request closed without merging**
