### PR TITLE
updated italian translations

### PR DESCRIPTION
**Pull request by andrerinaldi**
Added translations for Italian language.

### CODE REVIEW

**Comment by gioggi** [comment]
I think there is an error, please Andrea make a check on  line 67
```
 <source/>
      <translation type="unfinished"/>
    </message>
    <message>
      <source/>
      <translation type="unfinished"/>
    </message>
    <message>
    <message>
```

**Comment by andrerinaldi** [comment]
> I think there is an error, please Andrea make a check on line 67
> 
> ```
>  <source/>
>       <translation type="unfinished"/>
>     </message>
>     <message>
>       <source/>
>       <translation type="unfinished"/>
>     </message>
>     <message>
>     <message>
> ```

That line was like that also before my commit and I didn't notice.. anyway.. removed, since in other translation files that line is not present.

**Review by gioggi — CHANGES_REQUESTED** [review]
please check line 60

**Review by gioggi — APPROVED** [review]

**Comment by remdex** [comment]
As discussed translations has to got through https://explore.transifex.com/remigijus-kiminas/live-helper-chat/

**Pull request closed without merging**
