### PR TITLE
fixed cron notification include file error

### PR DESCRIPTION
**Pull request by MesutErdemir**

### CODE REVIEW

**Comment by remdex** [comment]
This is already in master branch.
https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/modules/lhcron/notifications.php

**Comment by MesutErdemir** [comment]
Yes but this file is not exist and not need to include.

include 'lib/vendor/autoload.php';

**Comment by remdex** [comment]
But if you do composer install this file would appear and as this cronjob is intended to work only if composer part is solved. This change you did is wrong... Better would be just if file_exists if you want to create another pull request :)

**Comment by MesutErdemir** [comment]
You're right, I noticed composer.json config variable :)

**Pull request closed without merging**
