### PR TITLE
small bug

### PR DESCRIPTION
**Pull request by intika**
small bug where we have a "«" in the title of the pop up window, should not be there

### CODE REVIEW

**Comment by remdex** [comment]
How to reproduce your mentioned bug?

**Comment by intika** [comment]
just open the chat as a popup and have a look at the title of the window value

**Comment by remdex** [comment]
I did and i cannot see a issue. Can you reproduce issue on http://demo.livehelperchat.com and just paste url here.

**Comment by intika** [comment]
http://postimg.org/image/7alpf1255/
here is a capture

**Comment by remdex** [comment]
This is not a bug, this character is intentionally there :)

**Comment by intika** [comment]
ok ;)
(but if you meant to display "<< live helper chat >>" then the other side ">>" is not present)

**Comment by intika** [comment]
any way ;)

**Comment by remdex** [comment]
No I mean present what is presented :)

**Comment by intika** [comment]
okay a king a "=>" :)

**Pull request closed without merging**
